/**
 * Browser-safe frontmatter parser — replaces gray-matter in the renderer process.
 *
 * gray-matter depends on Node.js `Buffer` which isn't available in browser/Vite
 * dev-server contexts (see ipc-state.md §5). This module provides a drop-in
 * replacement that handles the YAML subset generated by Study Parlor's own
 * `serializeFrontmatter()` in electron/lib/frontmatter.ts.
 *
 * Handles: scalars, quoted strings, numbers, booleans, block arrays (- item).
 * Does NOT handle: inline arrays [a,b], nested objects in arrays, multi-line
 * strings — none of which are needed by the renderer-side consumers
 * (ReportHeader, fileType detection).
 */

import type { Frontmatter } from '@shared/index'

// ── YAML scalar parsing ────────────────────────────────────────────────

function parseScalar(val: string): unknown {
  if (val === 'true' || val === 'false') return val === 'true'
  if (val === 'null' || val === '~' || val === '[]') return null
  if (/^-?\d+$/.test(val)) return parseInt(val, 10)
  if (/^-?\d+\.\d+$/.test(val)) return parseFloat(val)
  // Strip surrounding single or double quotes
  if ((val.startsWith("'") && val.endsWith("'")) ||
      (val.startsWith('"') && val.endsWith('"'))) {
    return val.slice(1, -1)
  }
  return val
}

// ── Simple YAML block parser ───────────────────────────────────────────

function parseSimpleYaml(yaml: string): Record<string, unknown> {
  const result: Record<string, unknown> = {}
  const lines = yaml.split('\n')
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    // Skip empty / whitespace-only lines
    if (line.trim() === '') {
      i++
      continue
    }

    // Top-level key: value (or key: with block value on following lines)
    const topMatch = line.match(/^(\w[\w_]*):\s*(.*)/)
    if (topMatch) {
      const key = topMatch[1]
      const rest = topMatch[2].trim()

      if (rest === '') {
        // Value is on following lines — check for block array ("  - item")
        const arrayItems: unknown[] = []
        let j = i + 1
        while (j < lines.length) {
          const nextLine = lines[j]
          const itemMatch = nextLine.match(/^\s+-\s+(.*)/)
          if (itemMatch) {
            arrayItems.push(parseScalar(itemMatch[1].trim()))
            j++
          } else {
            break
          }
        }
        if (arrayItems.length > 0) {
          result[key] = arrayItems
          i = j
          continue
        }
        // Empty value with no block children — store as empty string
        result[key] = ''
        i++
        continue
      }

      result[key] = parseScalar(rest)
      i++
      continue
    }

    i++
  }

  return result
}

// ── Public API ─────────────────────────────────────────────────────────

/** Drop-in replacement for gray-matter's default export. */
export function matter(raw: string): { data: Record<string, unknown>; content: string } {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/)
  if (!match) {
    return { data: {}, content: raw }
  }
  return {
    data: parseSimpleYaml(match[1]),
    content: raw.slice(match[0].length),
  }
}

/**
 * Browser-safe replacement for `parseFrontmatter()` from
 * `@electron/lib/frontmatter`. Returns structured Frontmatter + body.
 *
 * Only populates fields that the renderer actually consumes (ReportHeader
 * display, fileType detection). Other Frontmatter fields remain `undefined`.
 */
export function parseFrontmatterSafe(
  raw: string,
  opts?: { filename?: string },
): { frontmatter: Frontmatter; body: string } {
  const { data, content } = matter(raw)

  const frontmatter: Frontmatter = {
    title: (data.title as string) ??
      opts?.filename?.replace(/\.md$/i, '') ??
      'untitled',
    created: (data.created as string) ?? new Date().toISOString(),
    review_count: typeof data.review_count === 'number' ? data.review_count : 0,
    difficulty: (data.difficulty as 'high' | 'mid' | 'low') ?? 'mid',
    tags: Array.isArray(data.tags) ? (data.tags as string[]) : [],

    // Optional fields used by ReportHeader
    type: data.type as Frontmatter['type'],
    description: data.description as string | undefined,
    session_number: typeof data.session_number === 'number'
      ? data.session_number
      : undefined,
    last_reviewed: data.last_reviewed as string | undefined,
    last_studied: data.last_studied as string | undefined,
    progress_summary: data.progress_summary as string | undefined,
  }

  return { frontmatter, body: content }
}

/**
 * Extract a single field value from YAML frontmatter without full parsing.
 * Used by fileType.ts for lightweight `type` field extraction.
 */
export function extractFrontmatterField(raw: string, field: string): string | undefined {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!match) return undefined
  const re = new RegExp(`^${field}:\\s*(.+)`, 'm')
  const fmMatch = match[1].match(re)
  if (!fmMatch) return undefined
  return fmMatch[1].trim().replace(/^['"]|['"]$/g, '')
}
