export type Quote = {
  id: string
  text: string
  original?: string
  author: string
  authorOriginal?: string
  source?: string
}

export const quotes: Quote[] = [
  {
    id: "blanchot-01",
    text: "但我的沉默是真实的。如果我把它藏了起来，你也会在稍远处重新找到它。",
    original: "Mais mon silence est réel. Si je vous le cachais, vous le retrouveriez un peu plus loin.",
    author: "莫里斯·布朗肖",
    source: "《文学空间》",
  },
  {
    id: "blanchot-02",
    text: "只表达那无法被表达的东西。让它不被表达。",
    original: "N'exprimer que l'inexprimable. Le laisser inexprimé.",
    author: "莫里斯·布朗肖",
    source: "《文学空间》",
  },
  {
    id: "blanchot-03",
    text: "在夜里，沉默就是言说，没有安息，因为没有任何位置。",
    original: "Dans la nuit, le silence est parole, et il n'y a pas de repos, car il n'y a pas de position.",
    author: "莫里斯·布朗肖",
    source: "《文学空间》",
  },
  {
    id: "blanchot-04",
    text: "灾难摧毁一切，同时让一切保持原样。",
    original: "Le désastre ruine tout, tout en laissant tout intact.",
    author: "莫里斯·布朗肖",
    source: "《灾异的书写》",
  },
  {
    id: "blanchot-05",
    text: "失眠的白夜——这就是灾异：没有黑暗的夜，但也没有被任何光明照亮。",
    original: "Nuit ; blanche, sans sommeil — telle est le désastre : la nuit privée de ténèbres, mais éclairée par aucune lumière.",
    author: "莫里斯·布朗肖",
    source: "《灾异的书写》",
  },
  {
    id: "blanchot-06",
    text: "写作，就是走向那个永不到来的终点。",
    original: "Écrire, c'est cheminer vers ce point où l'on n'arrive jamais.",
    author: "莫里斯·布朗肖",
    source: "《文学空间》",
  },
  {
    id: "kafka-01",
    text: "阅读是砍向我们内心冰封大海的斧头",
    original: "Ein Buch muß die Axt sein für das gefrorene Meer in uns.",
    author: "弗兰茨·卡夫卡",
    source: "致奥斯卡·波拉克的信，1904",
  },
  {
    id: "kafka-02",
    text: "写作是彻底的孤独，是坠入自身冰冷的深渊。",
    original: "Schreiben ist die vollkommene Einsamkeit, der Abstieg in die kalte Tiefe von sich selbst.",
    author: "弗兰茨·卡夫卡",
    source: "《日记》",
  },
  {
    id: "kafka-03",
    text: "你不必离开你的房间。坐在桌旁别动。听。甚至不必听，只需等待。安静、静止、孤独。世界会自愿在你面前揭开面纱。",
    original: "Du brauchst dein Zimmer nicht verlassen. Bleib am Tisch sitzen und horche... Die Welt wird sich dir freiwillig entblößen.",
    author: "弗兰茨·卡夫卡",
    source: "《苏劳箴言》",
  },
  {
    id: "kafka-04",
    text: "我写下的东西与我所说的话不同，我所说的话与我想的不同，我想的与我认为应该想的不同，于是就这样一直深入最黑暗之中。",
    original: "Ich schreibe anders, als ich spreche, ich spreche anders, als ich denke...",
    author: "弗兰茨·卡夫卡",
    source: "《日记》",
  },
  {
    id: "kafka-05",
    text: "我的孤独有一种力量，它从不失效。",
    original: "Die Einsamkeit hat eine Macht über mich, die nie versagt.",
    author: "弗兰茨·卡夫卡",
    source: "《日记》，1913",
  },
  {
    id: "kafka-06",
    text: "我所取得的一切，只是孤独的成果。",
    original: "Was ich geleistet habe, ist nur ein Erfolg des Alleinseins.",
    author: "弗兰茨·卡夫卡",
    source: "《日记》，1913",
  },
  {
    id: "kafka-07",
    text: "城堡近在咫尺，却永远无法抵达。",
    original: "Das Schloss lag über dem Dorf, und doch war es unerreichbar.",
    author: "弗兰茨·卡夫卡",
    source: "《城堡》",
  },
  {
    id: "kafka-08",
    text: "沉默不是无话可说，而是话语在抵达之前就已经消散。",
    original: "Schweigen ist nicht das Fehlen von Worten, sondern das Verschwinden der Worte vor ihrer Ankunft.",
    author: "弗兰茨·卡夫卡",
    source: "《致米莱娜的信》",
  },
  {
    id: "kafka-10",
    text: "一只笼子去寻找一只鸟。",
    original: "Ein Käfig ging einen Vogel suchen.",
    author: "弗兰茨·卡夫卡",
    source: "残篇",
  },
  {
    id: "borges-01",
    text: "时间永远分叉，通向无数的未来。",
    original: "El tiempo se bifurca perpetuamente hacia innumerables futuros.",
    author: "豪尔赫·路易斯·博尔赫斯",
    source: "《小径分岔的花园》",
  },
  {
    id: "calvino-01",
    text: "写作永远意味着藏起什么东西，以便之后被发现。",
    original: "Scrivere è sempre nascondere qualcosa in modo che venga poi scoperto.",
    author: "伊塔洛·卡尔维诺",
    source: "《如果在冬夜，一个旅人》",
  },
  {
    id: "calvino-02",
    text: "一个人读书，即使在别人身边，也是独自在阅读。",
    original: "Si legge soli, anche in presenza di altri.",
    author: "伊塔洛·卡尔维诺",
    source: "《为什么读经典》",
  },
  {
    id: "calvino-03",
    text: "只有通过写作这种限制性的行为，未写之物的浩瀚才变得可读。",
    original: "È solo attraverso l'atto confinante della scrittura che l'immensità del non scritto diventa leggibile.",
    author: "伊塔洛·卡尔维诺",
    source: "《美国讲稿》",
  },
  {
    id: "calvino-04",
    text: "城市就像梦境：所有可以想象到的都可以被梦到。",
    original: "Le città sono come i sogni: tutto ciò che si immagina può essere sognato.",
    author: "伊塔洛·卡尔维诺",
    source: "《看不见的城市》",
  },
  {
    id: "rilke-01",
    text: "爱在于此：两个孤独彼此保护、触碰和问候。",
    original: "Liebe besteht darin, daß zwei Einsamkeiten einander schützen, grenzen und grüßen.",
    author: "赖内·马利亚·里尔克",
    source: "《给青年诗人的信》",
  },
  {
    id: "rilke-02",
    text: "未来站在我们中间，为了一个已经发生的吻。",
    original: "Die Zukunft steht vor uns, um eines schon geschehenen Kusses willen.",
    author: "赖内·马利亚·里尔克",
    source: "《杜伊诺哀歌》",
  },
  {
    id: "proust-01",
    text: "真正的发现之旅不在于寻找新的景观，而在于拥有新的目光。",
    original: "Le véritable voyage de découverte ne consiste pas à chercher de nouveaux paysages, mais à avoir de nouveaux yeux.",
    author: "马塞尔·普鲁斯特",
    source: "《追忆似水年华》",
  },
  {
    id: "proust-02",
    text: "唯一真实的乐园是我们已经失去的乐园，唯一有吸引力的世界是我们尚未踏入的世界。",
    original: "Les vrais paradis sont les paradis qu'on a perdus.",
    author: "马塞尔·普鲁斯特",
    source: "《重现的时光》",
  },
  {
    id: "proust-03",
    text: "每天清晨有多少双眼睛睁开，有多少人的意识苏醒过来，便有多少个世界。",
    author: "马塞尔·普鲁斯特",
    source: "《追忆似水年华》",
  },
  {
    id: "proust-05",
    text: "对于爱着的人来说，缺席难道不是最确定、最有效、最鲜活、最不可摧毁、最忠实的在场吗？",
    original: "L'absence n'est-elle pas, pour qui aime, la plus certaine, la plus efficace, la plus vivace, la plus indestructible, la plus fidèle des présences ?",
    author: "马塞尔·普鲁斯特",
    source: "《欢乐与时日》",
  },
  {
    id: "proust-06",
    text: "一个睡着的人围绕自己圈起了时间的丝线、年份的秩序和世界的秩序。",
    original: "Un homme qui dort tient en cercle autour de lui le fil des heures, l'ordre des années et des mondes.",
    author: "马塞尔·普鲁斯特",
    source: "《在斯万家那边》",
  },
  {
    id: "camus-01",
    text: "为了理解世界，人有时必须背过身去。",
    author: "阿尔贝·加缪",
    source: "《西西弗神话》",
  },
  {
    id: "woolf-01",
    text: "这时她用不着顾忌任何人，她可以独处，可以处于自然状态。这正是现在她常常感到需要的——思考；哦，甚至连思考也不要。只要静默；独自一人，一切外扩的、绚丽的、语言的存在和行为都消失了；人怀着庄严感缩回自我，一个楔形的隐秘的内核，是别人所看不见的。",
    author: "弗吉尼亚·伍尔夫",
    source: "《到灯塔去》",
  },
  {
    id: "woolf-03",
    text: "为了怀抱一些新幻想，我们失去一些旧幻想，这就是成长。",
    author: "弗吉尼亚·伍尔夫",
    source: "《一间自己的房间》",
  },
  {
    id: "woolf-04",
    text: "我扎根，但我流动。",
    original: "I am rooted, but I flow.",
    author: "弗吉尼亚·伍尔夫",
    source: "《海浪》",
  },
  {
    id: "woolf-05",
    text: "生命不是一系列对称排列的灯；它是一圈光晕，一个半透明的容器，围绕着我们无法命名的光。",
    original: "Life is not a series of gig-lamps symmetrically arranged; life is a luminous halo.",
    author: "弗吉尼亚·伍尔夫",
    source: "《现代小说》",
  },
  {
    id: "gide-01",
    text: "我不再理解'孤独'这个词；独处于自身之中，就是不再成为任何人；我被人充满。",
    author: "安德烈·纪德",
    source: "《人间食粮》",
  },
  {
    id: "gide-02",
    text: "人必须始终跳出自己，又落回自己——跳得更高，落得更深。",
    author: "安德烈·纪德",
    source: "《人间食粮》",
  },
  {
    id: "cortazar-01",
    text: "我们无需寻找彼此，却知道我们行走是为了相遇。",
    original: "Andábamos sin buscarnos, pero sabiendo que andábamos para encontrarnos.",
    author: "胡里奥·科塔萨尔",
    source: "《跳房子》",
  },
  {
    id: "cortazar-02",
    text: "记忆编织我们的同时也困住我们，按照一种我们不参与制定的方案。",
    author: "胡里奥·科塔萨尔",
    source: "《跳房子》",
  },
  {
    id: "cortazar-03",
    text: "怀旧，当一个人任由那些我们称之为回忆的缺席所腐蚀，而必须用词语和图像去缝补那样一种无法满足的空虚。",
    author: "胡里奥·科塔萨尔",
    source: "《游戏的终结》",
  },
  {
    id: "cortazar-04",
    text: "时间是一只被关在屋子里的野兽，我们只好与它同住。",
    original: "El tiempo es una bestia encerrada en la casa y hay que habitar con ella.",
    author: "胡里奥·科塔萨尔",
    source: "《万火归一》",
  },
  {
    id: "bolano-01",
    text: "阅读就像思考，就像祈祷，就像与朋友交谈，就像表达你的想法，就像倾听他人的想法，就像听音乐，就像看风景，就像在海滩上散步。",
    author: "罗贝托·波拉尼奥",
    source: "《荒野侦探》",
  },
  {
    id: "bolano-02",
    text: "作品是在通往孤独的路上踏过一串骨头。",
    author: "罗贝托·波拉尼奥",
    source: "《荒野侦探》",
  },
  {
    id: "bolano-04",
    text: "对我来说，'写作'这个词恰好是'等待'的反义词。不是等待，而是写作。",
    author: "罗贝托·波拉尼奥",
    source: "访谈",
  },
  {
    id: "bolano-05",
    text: "文学是刺客们最后的避难所。",
    original: "La literatura es el último refugio de los asesinos.",
    author: "罗贝托·波拉尼奥",
    source: "《护身符》",
  },
  {
    id: "marquez-01",
    text: "生活不是一个人活过的日子，而是一个人记得的日子，以及他记得的方式，为了讲述它。",
    author: "加夫列尔·加西亚·马尔克斯",
    source: "《活着为了讲述》",
  },
  {
    id: "marquez-02",
    text: "是生活，而非死亡，才没有止境。",
    author: "加夫列尔·加西亚·马尔克斯",
    source: "《霍乱时期的爱情》",
  },
  {
    id: "marquez-03",
    text: "人类并非永远在他们母亲生下他们的那一天诞生，而是生活迫使他们一次又一次地自我诞生。",
    author: "加夫列尔·加西亚·马尔克斯",
    source: "《霍乱时期的爱情》",
  },
  {
    id: "marquez-04",
    text: "孤独是爱的最深处。",
    original: "La soledad es el fondo del amor.",
    author: "加夫列尔·加西亚·马尔克斯",
    source: "《霍乱时期的爱情》",
  },
  {
    id: "arendt-01",
    text: "思考本身，就是与自我的无声对话。",
    original: "Thinking itself is a silent dialogue between me and myself.",
    author: "汉娜·阿伦特",
    source: "《The Life of the Mind》",
  },
  {
    id: "arendt-02",
    text: "在孤独中，一个人与自己同在；在独处中，一个人与自己合一。",
    author: "汉娜·阿伦特",
    source: "《The Life of the Mind》",
  },
  {
    id: "arendt-03",
    text: "每一个开端，都内含着一个奇迹。",
    author: "汉娜·阿伦特",
    source: "《The Human Condition》",
  },
  {
    id: "arendt-04",
    text: "最危险的人，是那些不再能区分事实与虚构的人。",
    author: "汉娜·阿伦特",
    source: "《The Origins of Totalitarianism》",
  },
  {
    id: "nietzsche-01",
    text: "在孤独中，每一个创造者都生长。",
    original: "In der Einsamkeit wächst, was irgend geschaffen werden soll.",
    author: "弗里德里希·尼采",
    source: "《查拉图斯特拉如是说》",
  },
  {
    id: "nietzsche-02",
    text: "没有音乐，生命将是一个错误。",
    original: "Ohne Musik wäre das Leben ein Irrtum.",
    author: "弗里德里希·尼采",
    source: "《偶像的黄昏》",
  },
  {
    id: "wittgenstein-01",
    text: "哲学是一场对抗语言对我们理智的蛊惑的战斗。",
    author: "路德维希·维特根斯坦",
    source: "《哲学研究》",
  },
  {
    id: "heidegger-01",
    text: "思考即感谢。",
    original: "Das Denken ist ein Danken.",
    author: "马丁·海德格尔",
    source: "《What is Called Thinking?》",
  },
  {
    id: "heidegger-02",
    text: "语言是存在的家。",
    original: "Die Sprache ist das Haus des Seins.",
    author: "马丁·海德格尔",
    source: "《论人道主义的信》",
  },
  {
    id: "heidegger-03",
    text: "焦虑揭示了虚无，而虚无揭示了存在。",
    author: "马丁·海德格尔",
    source: "《存在与时间》",
  },
  {
    id: "plato-01",
    text: "我们在黑暗中摸索，仿佛置身于洞穴之中。",
    author: "柏拉图",
    source: "《理想国》第七卷",
  },
  {
    id: "plato-02",
    text: "学习是回忆。",
    original: "μάθησις οὐκ ἄλλο τι ἢ ἀνάμνησις.",
    author: "柏拉图",
    source: "《美诺篇》",
  },
  {
    id: "aristotle-01",
    text: "智慧不在于知道一切，而在于知道什么是最重要的。",
    author: "亚里士多德",
    source: "《尼各马可伦理学》",
  },
  {
    id: "hegel-01",
    text: "真理是全体。",
    author: "格奥尔格·威廉·弗里德里希·黑格尔",
    source: "《精神现象学》",
  },
  {
    id: "marx-01",
    text: "哲学家们只是用不同的方式解释世界，而问题在于改变世界。",
    author: "卡尔·马克思",
    source: "《关于费尔巴哈的提纲》",
  },
  {
    id: "marx-02",
    text: "商品乍看之下是一种极其简单、平凡的东西。但分析表明，它实际上是一种古怪的东西，充满了形而上学的微妙和神学的怪癖。",
    original: "Die Ware erscheint zunächst als ein äußerst selbstverständliches, triviales Ding... voll metaphysischer Spitzfindigkeit und theologischer Mucken.",
    author: "卡尔·马克思",
    source: "《资本论》第一卷",
  },
  {
    id: "aurelius-01",
    text: "人的生命只是一瞬间，本质在于用好这一瞬间。",
    author: "马可·奥勒留",
    source: "《沉思录》",
  },
  {
    id: "aurelius-02",
    text: "在宁静中，灵魂才能找到它的归宿。",
    author: "马可·奥勒留",
    source: "《沉思录》",
  },
  {
    id: "epictetus-01",
    text: "首先告诉自己你想成为什么样的人，然后去做你必须做的事。",
    author: "爱比克泰德",
    source: "《手册》",
  },
  {
    id: "epictetus-02",
    text: "真正的财富不是拥有很多，而是需要很少。",
    author: "爱比克泰德",
    source: "《手册》",
  },
  {
    id: "epictetus-03",
    text: "没有人能伤害你，除非你允许。",
    author: "爱比克泰德",
    source: "《手册》",
  },
  {
    id: "seneca-01",
    text: "不是因为事情难，我们不敢；而是因为我们不敢，事情才难。",
    author: "塞涅卡",
    source: "《书信集》",
  },
  {
    id: "seneca-02",
    text: "真正伟大的灵魂，是在孤独中发现自己的人。",
    author: "塞涅卡",
    source: "《论心灵的宁静》",
  },
  {
    id: "seneca-04",
    text: "生命并非短促，而是我们荒废太多。",
    author: "塞涅卡",
    source: "《论生命的短暂》",
  },
  {
    id: "bible-01",
    text: "凡事都有定期，天下万务都有定时……静默有时，言语有时。",
    original: "For everything there is a season... a time to keep silence, and a time to speak.",
    author: "圣经",
    source: "《传道书》3:1, 7",
  },
  {
    id: "bible-02",
    text: "我的心默默无声，专等候神。",
    original: "For God alone my soul waits in silence.",
    author: "圣经",
    source: "《诗篇》62:1",
  },
  {
    id: "buddhist-sutras-01",
    text: "彼于战场得胜，生擒千人；然能克己者，实最上之战。",
    author: "佛经",
    source: "《法句经·双要品》",
  },
  {
    id: "cioran-01",
    text: "生命毫无意义，这一事实本身就是活下去的理由——而且是唯一的理由。",
    original: "Le fait que la vie n'ait pas de sens est une raison de vivre — et la seule.",
    author: "齐奥朗",
    source: "《生于不便》",
  },
  {
    id: "cioran-02",
    text: "从清晨到夜晚，你在做什么？我在忍受我自己。",
    original: "Que faites-vous du matin au soir ? Je m'endure.",
    author: "齐奥朗",
    source: "《生于不便》",
  },
  {
    id: "cioran-03",
    text: "只有失眠者知道夜晚的质地。",
    original: "Seul l'insomniaque connaît la texture de la nuit.",
    author: "齐奥朗",
    source: "《解体概要》",
  },
  {
    id: "beckett-01",
    text: "没有什么比虚无更真实。",
    original: "Nothing is more real than nothing.",
    author: "贝克特",
    source: "《马龙之死》",
  },
  {
    id: "beckett-02",
    text: "我无法继续。我会继续。",
    original: "I can't go on. I'll go on.",
    author: "贝克特",
    source: "《无名者》",
  },
  {
    id: "dostoevsky-01",
    text: "苦难是意识的唯一起源。",
    original: "Страдание есть единственное основание сознания.",
    author: "陀思妥耶夫斯基",
    source: "《地下室手记》",
  },
  {
    id: "dostoevsky-02",
    text: "我向你发誓，先生们，过度意识是一种疾病，一种真正的、彻头彻尾的疾病。",
    original: "I swear to you, gentlemen, that being overly conscious is a disease, a genuine, full-fledged disease.",
    author: "陀思妥耶夫斯基",
    source: "《地下室手记》",
  },
  {
    id: "dostoevsky-03",
    text: "我承认二二得四是个极好的东西，但倘若事事都该各得其所，那么二二得五有时也是极其迷人的东西。",
    original: "I admit that twice two makes four is an excellent thing, but if we are to give everything its due, twice two makes five is sometimes a very charming thing too.",
    author: "陀思妥耶夫斯基",
    source: "《地下室手记》",
  },
  {
    id: "dostoevsky-04",
    text: "夜越黑，星星越明亮；悲伤越深，上帝越近。",
    original: "The darker the night, the brighter the stars, The deeper the grief, the closer is God!",
    author: "陀思妥耶夫斯基",
    source: "《罪与罚》",
  },
  {
    id: "dostoevsky-05",
    text: "美是神秘而可怕的。上帝与魔鬼在那里搏斗，战场是人的心灵。",
    original: "Beauty is mysterious as well as terrible. God and devil are fighting there, and the battlefield is the heart of man.",
    author: "陀思妥耶夫斯基",
    source: "《卡拉马佐夫兄弟》",
  },
  {
    id: "dostoevsky-06",
    text: "最重要的是，我们首先应该善良，其次要诚实，再次是以后永远不要相互遗忘。",
    original: "Above all, don't lie to yourself. The man who lies to himself... loses all respect for himself and for others.",
    author: "陀思妥耶夫斯基",
    source: "《卡拉马佐夫兄弟》",
  },
  {
    id: "dostoevsky-07",
    text: "地狱是什么？我认为，地狱就是'由于不能再爱而受到的痛苦'。",
    original: "What is hell? I maintain that it is the suffering of being unable to love.",
    author: "陀思妥耶夫斯基",
    source: "《卡拉马佐夫兄弟》",
  },
  {
    id: "dostoevsky-08",
    text: "人只喜欢数自己的不幸，却不计算自己的幸福。",
    original: "Man only likes to count his troubles; he doesn't calculate his happiness.",
    author: "陀思妥耶夫斯基",
    source: "《地下室手记》",
  },
  {
    id: "unamuno-01",
    text: "生命即怀疑，没有怀疑的信仰不过是死亡。",
    original: "La vida es duda, y la fe sin duda no es sino muerte.",
    author: "乌纳穆诺",
    source: "《生命的悲剧感》",
  },
  {
    id: "beauvoir-01",
    text: "我无法构想无限，却又无法接受有限。我希望这场构成我生命的冒险永无止境。",
    original: "Je suis incapable de concevoir l'infini, et pourtant je ne puis accepter le fini...",
    author: "波伏娃",
    source: "《老年》",
  },
  {
    id: "beauvoir-02",
    text: "没有所谓的自然死亡：发生在人身上的一切都不自然，因为他的存在使世界成为问题。",
    original: "Il n'y a pas de mort naturelle : rien de ce qui arrive à l'homme n'est jamais naturel...",
    author: "波伏娃",
    source: "《一场非常轻松的死亡》",
  },
  {
    id: "gadamer-01",
    text: "事实上，历史并不属于我们，而是我们属于它。",
    original: "In Wahrheit gehört die Geschichte nicht uns, sondern wir gehören ihr.",
    author: "伽达默尔",
    source: "《真理与方法》",
  },
  {
    id: "husserl-01",
    text: "回到事物本身。",
    original: "Zu den Sachen selbst.",
    author: "胡塞尔",
    source: "《逻辑研究》",
  },
  {
    id: "ricoeur-01",
    text: "自我，即另一个自我。",
    original: "Soi-même comme un autre.",
    author: "利科",
    source: "《作为另一个人的自我》",
  },
  {
    id: "merleau-ponty-01",
    text: "我的身体是世界的枢纽。",
    original: "Mon corps est le pivot du monde.",
    author: "梅洛-庞蒂",
    source: "《知觉现象学》",
  },
  {
    id: "zhuangzi-01",
    text: "天地与我并生，而万物与我为一。",
    author: "庄子",
    source: "《庄子·齐物论》",
  },
  {
    id: "zhuangzi-02",
    text: "天地有大美而不言。",
    author: "庄子",
    source: "《知北游》",
  },
  {
    id: "laozi-01",
    text: "致虚极，守静笃。万物并作，吾以观复。",
    author: "老子",
    source: "《道德经》第十六章",
  },
  {
    id: "laozi-02",
    text: "大直若屈，大巧若拙，大辩若讷。",
    author: "老子",
    source: "《道德经》第四十五章",
  },
  {
    id: "laozi-03",
    text: "大音希声，大象无形。",
    author: "老子",
    source: "《道德经》第四十一章",
  },
  {
    id: "taoyuanming-01",
    text: "此中有真意，欲辨已忘言。",
    author: "陶渊明",
    source: "《饮酒·其五》",
  },
  {
    id: "wangwei-01",
    text: "行到水穷处，坐看云起时。",
    author: "王维",
    source: "《终南别业》",
  },
  {
    id: "tagore-01",
    text: "我们把世界看错，反说它欺骗了我们。",
    original: "We read the world wrong and say that it deceives us.",
    author: "泰戈尔",
    source: "《飞鸟集》",
  },
  {
    id: "tagore-02",
    text: "绿草求她地上的伴侣，树木求他天空的寂寞。",
    original: "The grass seeks her crowd in the earth. The tree seeks his solitude of the sky.",
    author: "泰戈尔",
    source: "《飞鸟集》",
  },
  {
    id: "suzuki-01",
    text: "开悟不是获得新东西，而是觉醒到你本已拥有的一切。",
    original: "Satori is not acquiring something new, but awakening to what you already possess.",
    author: "铃木大拙",
    source: "《禅学入门》",
  },
  {
    id: "suzuki-02",
    text: "真的自由，是照着事物本来的样子去看它们，是去体会万有的本来面目。",
    original: "True freedom is seeing things as they are, experiencing the 'suchness' of all things.",
    author: "铃木大拙",
    source: "《禅与日本文化》",
  },
  {
    id: "eliot-01",
    text: "足音在记忆中回响，沿着我们未曾走过的通道，朝向那扇从未开启的门，通往玫瑰花园。",
    original: "Footfalls echo in the memory / Down the passage which we did not take / Towards the door we never opened / Into the rose-garden.",
    author: "T.S.艾略特",
    source: "《四个四重奏·烧毁的诺顿》",
  },
  {
    id: "eliot-02",
    text: "何处才能寻见那言辞，何处才能让那言辞回响？不是这里，这里的寂静不够深。",
    original: "Where shall the word be found, where will the word / Resound? Not here, there is not enough silence.",
    author: "T.S.艾略特",
    source: "《灰星期三》",
  },
  {
    id: "eliot-03",
    text: "这就是世界结束的方式。并非轰然一声，而是轻轻呜咽。",
    original: "This is the way the world ends / Not with a bang but a whimper.",
    author: "T.S.艾略特",
    source: "《空心人》",
  },
  {
    id: "eliot-04",
    text: "我们不应停止探索，而我们所有探索的终点，将是到达我们出发的地方，并且是第一次认识它。",
    original: "We shall not cease from exploration / And the end of all our exploring / Will be to arrive where we started / And know the place for the first time.",
    author: "T.S.艾略特",
    source: "《四个四重奏·小吉丁》",
  },
  {
    id: "eliot-05",
    text: "教我如何在意，又教我如何不在意；教我安然静坐。",
    original: "Teach me to care and not to care / Teach me to sit still.",
    author: "T.S.艾略特",
    source: "《灰星期三》",
  },
  {
    id: "rumi-01",
    text: "当我沉默，我便坠入那个万物皆乐音的地方。",
    original: "When I am silent, I fall into the place where everything is music.",
    author: "鲁米",
    source: "《鲁米诗集》",
  },
  {
    id: "rumi-02",
    text: "有一种声音不使用词语。去听。",
    original: "There is a voice that doesn't use words. Listen.",
    author: "鲁米",
    source: "《鲁米诗集》",
  },
  {
    id: "rumi-03",
    text: "我们从虚无中旋舞而出，将星辰如尘埃般撒落。",
    original: "از هیچ آمدیم و به هیچ رویم / نه از کینه و نه از مهر خداییم",
    author: "鲁米",
    source: "《沙姆斯集》第782首",
  },
  {
    id: "rumi-04",
    text: "让寂静带你抵达生命的核心。",
    original: "بگذار سکوت تو را به عمق زندگی ببرد",
    author: "鲁米",
    source: "《沙姆斯集》",
  },
  {
    id: "szymborska-01",
    text: "当我念出'未来'这个词，第一个音节已属过去。",
    original: "Kiedy wymawiam słowo Przyszłość, / pierwsza sylaba odchodzi już do przeszłości.",
    author: "维斯瓦娃·辛波斯卡",
    source: "《最奇怪的三个词》",
  },
  {
    id: "szymborska-03",
    text: "每一首诗都在提醒我们，我们是不完整的。",
    original: "Every poem reminds us that we are incomplete.",
    author: "维斯瓦娃·辛波斯卡",
    source: "《呼唤雪人》",
  },
  {
    id: "milosz-01",
    text: "我想我在这个世上，是为了呈交一份关于它的报告，但我不知道呈交给谁。",
    original: "I think that I am here, on this earth, to present a report on it, but to whom I don't know.",
    author: "切斯瓦夫·米沃什",
    source: "《意识》",
  },
  {
    id: "transtromer-01",
    text: "我被自己的影子携带，像一把小提琴在黑色的琴匣中。",
    original: "Jag bärs i min skugga / som en fiol / i sin svarta låda.",
    author: "托马斯·特朗斯特罗姆",
    source: "《四月与沉默》",
  },
  {
    id: "transtromer-03",
    text: "那空无一物之物转向我们，低语：'我并非空无一物，我是敞开的。'",
    original: "Och det tomma vänder sig till oss / och viskar: 'Jag är inte tom, jag är öppen.'",
    author: "托马斯·特朗斯特罗姆",
    source: "《罗马式穹顶》",
  },
  {
    id: "transtromer-02",
    text: "我醒来，世界还在那里，像一封未拆的信。",
    original: "Despierto: el mundo sigue ahí, como una carta sin abrir.",
    author: "托马斯·特朗斯特罗姆",
    source: "《半完成的天空》",
  },
  {
    id: "anaximander-01",
    text: "万物依必然性，从其所来之处而生，又向其而去毁灭；因为它们彼此为不正义付出代价和报偿，依时间的秩序。",
    original: "ἐξ ὧν ἡ γένεσίς ἐστι τοῖς οὖσι...",
    author: "阿那克西曼德",
    source: "残篇 B1",
  },
  {
    id: "epicurus-01",
    text: "我们只生一次，不可能再生。此后我们将永远不再存在。但你，既然不是明天的主人，却把快乐推迟。",
    original: "ἅπαξ γὰρ ἡμεῖς γενόμεθα, καὶ δὶς οὐκ ἔστι γενέσθαι...",
    author: "伊壁鸠鲁",
    source: "梵蒂冈语录第14条",
  },
  {
    id: "russell-01",
    text: "世间麻烦的根源在于，愚蠢的人总是信心满满，而聪明的人却充满怀疑。",
    original: "The fundamental cause of the trouble is that in the modern world the stupid are cocksure while the intelligent are full of doubt.",
    author: "伯特兰·罗素",
    source: "《愚蠢的胜利》",
  },
  {
    id: "russell-02",
    text: "我绝不会为我的信念而死，因为我可能是错的。",
    original: "I would never die for my beliefs because I might be wrong.",
    author: "伯特兰·罗素",
    source: "《我的信念》",
  },
  {
    id: "russell-03",
    text: "能够明智地填充闲暇，是文明的最后产物。",
    original: "To be able to fill leisure intelligently is the last product of civilization...",
    author: "伯特兰·罗素",
    source: "《幸福之路》",
  },
  {
    id: "russell-04",
    text: "恐惧是迷信的主要来源，也是残忍的主要来源之一。征服恐惧是智慧的开端。",
    original: "Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom.",
    author: "伯特兰·罗素",
    source: "《非通俗文集》",
  },
  {
    id: "russell-05",
    text: "好的生活由爱激发，由知识引导。",
    original: "The good life is one inspired by love and guided by knowledge.",
    author: "伯特兰·罗素",
    source: "《我相信什么》",
  },
  {
    id: "russell-06",
    text: "科学是你所知道的，哲学是你所不知道的。",
    original: "Science is what you know, philosophy is what you don't know.",
    author: "伯特兰·罗素",
    source: "《罗素谈思想》",
  },
  {
    id: "popper-01",
    text: "我们的知识只能是有限的，而我们的无知必然是无限的。",
    original: "Our knowledge can only be finite, while our ignorance must necessarily be infinite.",
    author: "卡尔·波普尔",
    source: "英国学院演讲",
  },
  {
    id: "popper-02",
    text: "科学可以被描述为系统过度简化的艺术。",
    original: "Science may be described as the art of systematic over-simplification.",
    author: "卡尔·波普尔",
    source: "《开放的宇宙》",
  },
  {
    id: "san-juan-de-la-cruz-01",
    text: "我停驻，我忘却，我的脸倚靠在至爱者身上；一切止息，我将自己交出，将我的挂虑遗忘在百合花丛中。",
    original: "Quedéme y olvidéme, el rostro recliné sobre el Amado...",
    author: "圣十字若望",
    source: "《心灵的黑夜》",
  },
  {
    id: "san-juan-de-la-cruz-02",
    text: "若要拥有一切，就不要在任何事上拥有什么。若要成为一切，就不要在任何事上成为什么。",
    original: "Para venir a poseerlo todo, no quieras poseer algo en nada...",
    author: "圣十字若望",
    source: "《攀登加尔默罗山》",
  },
  {
    id: "pseudo-dionysius-01",
    text: "我们祈祷进入那超越光明的黑暗，在不见不知中，看见并认识那超越一切所见与所知者。",
    original: "εὐχόμεθα ἐπὶ τὸν ὑπὲρ φῶς σκότους ἐλθεῖν...",
    author: "伪狄奥尼修斯",
    source: "《神秘神学》第一章",
  },
  {
    id: "dogen-01",
    text: "学道即学自己。学自己即忘自己。忘自己即被万法所印证。",
    original: "仏道をならふといふは、自己をならふ也。自己をならふといふは、自己をわするるなり...",
    author: "道元",
    source: "《正法眼蔵·現成公案》",
  },
  {
    id: "weil-01",
    text: "注意是最稀有、最纯粹的慷慨形式。",
    original: "L'attention est la forme la plus rare et la plus pure de la générosité.",
    author: "西蒙娜·薇依",
    source: "致乔·布斯凯的信，1942",
  },
  {
    id: "weil-02",
    text: "一切罪恶都是试图填补虚空。",
    original: "Tous les péchés sont des tentatives pour combler des vides.",
    author: "西蒙娜·薇依",
    source: "《重负与神恩》",
  },
  {
    id: "weil-03",
    text: "美是我们不想改变的东西。",
    original: "Le beau est ce que l'on ne peut pas désirer changer.",
    author: "西蒙娜·薇依",
    source: "《重负与神恩》",
  },
  {
    id: "weil-04",
    text: "在两个没有上帝经验的人之间，否认上帝的那个人也许离上帝更近。",
    original: "Entre deux hommes qui n'ont pas l'expérience de Dieu, celui qui le nie en est peut-être le plus près.",
    author: "西蒙娜·薇依",
    source: "《重负与神恩》",
  },
  {
    id: "weil-05",
    text: "我们最重要的思想应该是空的、等待的，不寻求任何东西，但准备好以赤裸的真理接受将要穿透它的对象。",
    original: "Above all our thought should be empty, waiting, not seeking anything, but ready to receive in its naked truth...",
    author: "西蒙娜·薇依",
    source: "《等待上帝》",
  },
  {
    id: "weil-06",
    text: "对受苦者付出注意力是一种非常罕见而困难的事；它几乎是一个奇迹；它就是一个奇迹。",
    original: "La capacité de donner son attention à un souffrant est une chose très rare et difficile ; c'est presque un miracle ; c'est un miracle.",
    author: "西蒙娜·薇依",
    source: "《等待上帝》",
  },
  {
    id: "weil-07",
    text: "危险不在于灵魂怀疑是否有面包，而在于灵魂通过谎言说服自己它并不饥饿。",
    original: "The danger is not lest the soul should doubt whether there is any bread, but lest, by a lie, it should persuade itself that it is not hungry.",
    author: "西蒙娜·薇依",
    source: "《等待上帝》",
  },
  {
    id: "weil-08",
    text: "扎根也许是人类灵魂最重要、却最不被认识的需要。",
    original: "Être enraciné est peut-être le besoin le plus important et le moins reconnu de l'âme humaine.",
    author: "西蒙娜·薇依",
    source: "《扎根的需要》",
  },
  {
    id: "weil-10",
    text: "只要还有上帝这个词，人就不会停止渴望。",
    original: "Tant qu'il y aura le mot Dieu, l'homme ne cessera de désirer.",
    author: "西蒙娜·薇依",
    source: "笔记",
  },
  {
    id: "shakespeare-01",
    text: "剩下的唯有沉默。",
    original: "The rest is silence.",
    author: "莎士比亚",
    source: "《哈姆雷特》",
  },
  {
    id: "shakespeare-02",
    text: "明天，又一个明天，又一个明天，在时间的碎步中一天天偷偷摸摸地爬行，直到记录时间的最后一个音节。",
    original: "Tomorrow, and tomorrow, and tomorrow, creeps in this petty pace from day to day, to the last syllable of recorded time.",
    author: "莎士比亚",
    source: "《麦克白》",
  },
  {
    id: "shakespeare-03",
    text: "人生不过是行走的影子，一个可怜的演员，在台上趾高气扬、焦躁不安地度过他的时光，然后便再也听不见。它是一个白痴所讲的故事，充满喧哗与骚动，却找不到一点意义。",
    original: "Life's but a walking shadow, a poor player that struts and frets his hour upon the stage, and then is heard no more. It is a tale told by an idiot, full of sound and fury, signifying nothing.",
    author: "莎士比亚",
    source: "《麦克白》",
  },
  {
    id: "shakespeare-04",
    text: "人类是一件多么了不得的杰作！多么高贵的理性！多么伟大的力量！……然而，在我眼中，这尘埃的精华又算得了什么？",
    original: "What a piece of work is a man! How noble in reason! How infinite in faculty!... and yet, to me, what is this quintessence of dust?",
    author: "莎士比亚",
    source: "《哈姆雷特》",
  },
  {
    id: "mishima-01",
    text: "不被人理解已经成为我唯一的自豪。所以，我也不会产生要让自己被理解的、表现的冲动。",
    original: "Not being understood by others has become my only pride. And so I have no impulse to make myself understood, no desire to express myself.",
    author: "三岛由纪夫",
    source: "《金阁寺》",
  },
  {
    id: "mishima-02",
    text: "人之形象容易毁灭，却浮现出永生的幻影；金阁之美固定不变，却渗透出毁灭的可能。",
    original: "The human figure is easily destroyed, yet it evokes the phantom of eternal life; the beauty of the Golden Pavilion is fixed and unchanging, yet it seeps with the possibility of destruction.",
    author: "三岛由纪夫",
    source: "《金阁寺》",
  },
  {
    id: "mishima-03",
    text: "用一只手去触摸永远，另一只手去触碰人生，这是不可能的。",
    original: "To touch eternity with one hand and life with the other—this is impossible.",
    author: "三岛由纪夫",
    source: "《金阁寺》",
  },
  {
    id: "li-zishu-01",
    text: "因为雨下得频繁，人生中不少重要的事好像都是在雨中发生的。那些记忆如今被掀开来感觉依然湿淋淋，即便干了，也像泡了水的书本一样，纸张全荡起波纹，难以平复。",
    author: "黎紫书",
    source: "《流俗地》",
  },
  {
    id: "li-zishu-02",
    text: "梦是说不得的，说了犹如摇晃一壶浊水，倒出来时所有细节便都混淆了。",
    author: "黎紫书",
    source: "《流俗地》",
  },
  {
    id: "mauriac-01",
    text: "像狗对月狂吠，我被一个倒影蛊惑。",
    original: "Comme un chien aboie à la lune, j'ai été fasciné par un reflet.",
    author: "弗朗索瓦·莫里亚克",
    source: "《蝰蛇之结》",
  },
  {
    id: "mauriac-02",
    text: "爱不是燃烧，而是一场缓慢的窒息。",
    original: "L'amour n'est pas une flamme, mais une suffocation lente.",
    author: "弗朗索瓦·莫里亚克",
    source: "《苔蕾丝·德斯盖鲁》",
  },
  {
    id: "levi-strauss-01",
    text: "我讨厌旅行和探险家。然而，我却要来讲述我的探险。",
    original: "Je hais les voyages et les explorateurs. Et voici que je m'apprête à raconter mes expéditions.",
    author: "克洛德·列维-斯特劳斯",
    source: "《忧郁的热带》",
  },
  {
    id: "mao-01",
    text: "俱往矣，数风流人物，还看今朝。",
    author: "毛泽东",
    source: "《沁园春·雪》",
  },
  {
    id: "mao-02",
    text: "问苍茫大地，谁主沉浮？",
    author: "毛泽东",
    source: "《沁园春·长沙》",
  },
  {
    id: "dickinson-03",
    text: "因为我不能停步等候死神，他殷勤地为我停下。",
    original: "Because I could not stop for Death – / He kindly stopped for me –",
    author: "艾米莉·狄金森",
    source: "《诗集》",
  },
  {
    id: "gluck-01",
    text: "在我痛苦的尽头，有一扇门。",
    original: "At the end of my suffering / there was a door.",
    author: "露易丝·格丽克",
    source: "《野鸢尾》",
  },
  {
    id: "vuong-01",
    text: "我写信，因为距离是言语能走的唯一的路。",
    original: "I write because distance is the only road language knows.",
    author: "王鸥行",
    source: "《大地上转瞬即逝的》",
  },
  {
    id: "sebald-02",
    text: "我从未理解过，一个人如何能在不迷路的情况下旅行。",
    original: "I have never understood how one can travel without getting lost.",
    author: "W. G. 塞巴尔德",
    source: "《土星之环》",
  },
  {
    id: "bernhard-01",
    text: "人是语言的受害者，而语言是世界的受害者。",
    original: "Der Mensch ist das Opfer der Sprache, und die Sprache ist das Opfer der Welt.",
    author: "托马斯·伯恩哈德",
    source: "《总统》",
  },
  {
    id: "celan-01",
    text: "世界已经离去，我必须背负你。",
    original: "Die Welt ist fort, ich muß dich tragen.",
    author: "保罗·策兰",
    source: "《呼吸结晶》",
  },
  {
    id: "bachmann-02",
    text: "真理对每个人都是可行的，只是代价不同。",
    original: "Die Wahrheit ist für jeden machbar, nur der Preis ist verschieden.",
    author: "英格博格·巴赫曼",
    source: "《马利纳》",
  },
  {
    id: "mandelstam-01",
    text: "我回到了我的城市，熟悉如眼泪、如静脉、如童年的腮腺炎。",
    original: "Я вернулся в мой город, знакомый до слёз, / До прожилок, до детских припухлых желез.",
    author: "奥西普·曼德尔施塔姆",
    source: "《列宁格勒》",
  },
  {
    id: "tsvetaeva-01",
    text: "我爱自己的不幸，胜过爱你们的幸福。",
    original: "Я люблю свое несчастье больше вашего счастья.",
    author: "玛琳娜·茨维塔耶娃",
    source: "书信",
  },
  {
    id: "brodsky-02",
    text: "一个人若不能独自生活，便不能与人共同生活。",
    original: "One who cannot live alone cannot live with others.",
    author: "约瑟夫·布罗茨基",
    source: "《小于一》",
  },
  {
    id: "sepehri-01",
    text: "我们应该慢慢走，以便灵魂跟上来。",
    original: "We should walk slowly, so that the soul can catch up.",
    author: "索赫拉布·塞佩里",
    source: "《脚步声》",
  },
  {
    id: "hikmet-01",
    text: "我来自东方，我的伤口是一张地图。",
    original: "I come from the east; my wound is a map.",
    author: "纳齐姆·希克梅特",
    source: "《人性风景》",
  },
  {
    id: "pamuk-01",
    text: "一本书是一座宫殿，读者是闯入其中的孤独窃贼。",
    original: "A book is a palace, and the reader a lonely thief who breaks in.",
    author: "奥尔罕·帕慕克",
    source: "《我的名字叫红》",
  },
  {
    id: "pamuk-02",
    text: "雪覆盖了一切，除了记忆。",
    original: "Snow covers everything except memory.",
    author: "奥尔罕·帕慕克",
    source: "《雪》",
  },
  {
    id: "tanpinar-01",
    text: "我渴望一种我尚未学会如何说出的语言。",
    original: "I long for a language I have not yet learned to speak.",
    author: "艾哈迈德·哈姆迪·坦皮纳尔",
    source: "《时间调校协会》",
  },
  {
    id: "tanpinar-02",
    text: "时间是最大的疾病，我们都在它的诊所里排队。",
    original: "Time is the greatest illness; we all wait in its clinic.",
    author: "艾哈迈德·哈姆迪·坦皮纳尔",
    source: "《时间调校协会》",
  },
  {
    id: "lispector-01",
    text: "我是一种如此古老的东西，以至于我不再知道自己是谁。",
    original: "Sou uma coisa tão antiga que já não sei quem sou.",
    author: "克拉丽丝·李斯佩克朵",
    source: "《濒于狂野的心》",
  },
  {
    id: "paz-02",
    text: "孤独是一面镜子，我们用它来确认自己的脸。",
    original: "La soledad es un espejo con el que reconocemos el rostro.",
    author: "奥克塔维奥·帕斯",
    source: "《孤独的迷宫》",
  },
  {
    id: "marti-01",
    text: "我肩上扛着两个祖国：黑夜与黎明。",
    original: "Llevo en los hombros dos patrias: la noche y la aurora.",
    author: "何塞·马蒂",
    source: "《简朴的诗》",
  },
  {
    id: "perec-01",
    text: "我问自己，当我什么也不做的时候，我在做什么。",
    original: "Je me demande ce que je fais quand je ne fais rien.",
    author: "乔治·佩雷克",
    source: "《尝试填补空白》",
  },
  {
    id: "jabes-01",
    text: "每一本书都是一座墙的缺口。",
    original: "Chaque livre est une brèche dans le mur.",
    author: "埃德蒙·雅贝斯",
    source: "《问题之书》",
  },
  {
    id: "glissant-01",
    text: "世界是可理解的，但不可总计。",
    original: "Le monde est compréhensible, mais il n'est pas totalisable.",
    author: "爱德华·格里桑",
    source: "《关系诗学》",
  },
  {
    id: "canetti-01",
    text: "词语是最后的避难所，也是最初的牢狱。",
    original: "Words are the last refuge and the first prison.",
    author: "埃利亚斯·卡内蒂",
    source: "《人的疆域》",
  },
  {
    id: "levi-01",
    text: "我们的记忆会背叛我们，这是我们唯一的自由。",
    original: "Our memory betrays us: this is our only freedom.",
    author: "普里莫·莱维",
    source: "《被淹没与被拯救的》",
  },
  {
    id: "trakl-01",
    text: "黑夜是一匹溺水的马。",
    original: "Die Nacht ist ein ertrinkendes Pferd.",
    author: "格奥尔格·特拉克尔",
    source: "《梦中的塞巴斯蒂安》",
  },
  {
    id: "trakl-02",
    text: "我腐烂在秋天的金色里。",
    original: "Ich vermoder im Gold des Herbstes.",
    author: "格奥尔格·特拉克尔",
    source: "《诗集》",
  },
  {
    id: "kawabata-02",
    text: "自杀而无遗书，是最好不过的。无言的死，就是无限的活。",
    author: "川端康成",
    source: "《不灭的美》",
  },
  {
    id: "luxun-02",
    text: "绝望之为虚妄，正与希望相同。",
    author: "鲁迅",
    source: "《希望》",
  },
  {
    id: "wangzengqi-02",
    text: "家人闲坐，灯火可亲。",
    author: "汪曾祺",
    source: "《冬天》",
  },
  {
    id: "zhang-ailing-01",
    text: "生命是一袭华美的袍，上面爬满了蚤子。",
    author: "张爱玲",
    source: "《天才梦》",
  },
  {
    id: "xichuan-01",
    text: "历史是一团灰烬，但灰烬深处尚有余温。",
    author: "西川",
    source: "《足够》",
  },
  {
    id: "ouyang-01",
    text: "玻璃是透明的伤口。",
    author: "欧阳江河",
    source: "《玻璃工厂》",
  },
  {
    id: "wangjiaxin-01",
    text: "我穿过语言的走廊，看见尽头是一盏熄灭的灯。",
    author: "王家新",
    source: "《雨夜》",
  },
  {
    id: "li-bai-01",
    text: "举杯邀明月，对影成三人。",
    author: "李白",
    source: "《月下独酌》",
  },
  {
    id: "li-bai-02",
    text: "夫天地者，万物之逆旅也；光阴者，百代之过客也。",
    author: "李白",
    source: "《春夜宴桃李园序》",
  },
  {
    id: "su-shi-01",
    text: "人生到处知何似，应似飞鸿踏雪泥。",
    author: "苏轼",
    source: "《和子由渑池怀旧》",
  },
  {
    id: "su-shi-02",
    text: "小舟从此逝，江海寄余生。",
    author: "苏轼",
    source: "《临江仙》",
  },
  {
    id: "su-shi-03",
    text: "回首向来萧瑟处，归去，也无风雨也无晴。",
    author: "苏轼",
    source: "《定风波》",
  },
  {
    id: "chang-jian-01",
    text: "曲径通幽处，禅房花木深。",
    author: "常建",
    source: "《题破山寺后禅院》",
  },
  {
    id: "haizi-01",
    text: "天空一无所有，为何给我安慰。",
    author: "海子",
    source: "《麦子》",
  },
]

export function pickRandomQuote(
  options: { excludeId?: string | null; pool?: Quote[] } = {}
): Quote | null {
  const pool = options.pool ?? quotes
  const excludeId = options.excludeId ?? null
  const filtered = excludeId ? pool.filter(q => q.id !== excludeId) : pool
  if (filtered.length === 0) return null
  return filtered[Math.floor(Math.random() * filtered.length)]
}
