export const SELECTORS = {
  cover: {
    nameInput: '[data-testid="cover-name-input"]',
    enterButton: '[data-testid="cover-enter-button"]',
    lightButton: '[data-testid="cover-light-button"]',
    briefingButton: '[data-testid="cover-briefing-button"]',
  },
  home: {
    greeting: '[data-testid="home-greeting"]',
    newTopicButton: '[data-testid="new-topic-button"]',
    librarySection: '[data-testid="library-section"]',
    continueUnsavedButton: '[data-testid="continue-unsaved-button"]',
    topicCard: '[data-testid="topic-card"]',
    topicContinueButton: '[data-testid="topic-continue-button"]',
    sessionReviewButton: '[data-testid="session-review-button"]',
  },
  preStudy: {
    modal: '[data-testid="prestudy-modal"]',
    topicInput: '[data-testid="topic-input"]',
    topicSourceNew: '[data-testid="topic-source-new"]',
    topicSourceExisting: '[data-testid="topic-source-existing"]',
    startButton: '[data-testid="start-button"]',
    cancelButton: '[data-testid="cancel-button"]',
  },
  study: {
    page: '[data-testid="study-page"]',
    messageList: '[data-testid="message-list"]',
    chatInput: '[data-testid="chat-input"]',
    sendButton: '[data-testid="send-button"]',
    archivePendingBanner: '[data-testid="archive-pending-banner"]',
    archiveButton: '[data-testid="archive-button"]',
    archiveReportClose: '[data-testid="archive-report-close"]',
    assistantMessage: '[data-testid="assistant-message"]',
    userMessage: '[data-testid="user-message"]',
  },
  quote: {
    text: '[data-testid="quote-text"]',
    original: '[data-testid="quote-original"]',
    meta: '[data-testid="quote-meta"]',
    refreshButton: 'button[aria-label="换一句"]',
  },
} as const
