export const SELECTORS = {
  cover: {
    nameInput: '[data-testid="cover-name-input"]',
    enterButton: '[data-testid="cover-enter-button"]',
    lightButton: '[data-testid="cover-light-button"]',
    briefingButton: '[data-testid="cover-briefing-button"]',
  },
  home: {
    greeting: '[data-testid="home-greeting"]',
    newTopicButton: '[data-testid="new-topic-button"]',
    librarySection: '[data-testid="library-section"]',
    continueUnsavedButton: '[data-testid="continue-unsaved-button"]',
    burnUnsavedButton: '[data-testid="burn-unsaved-button"]',
    unsavedSessionTitle: '[data-testid="unsaved-session-title"]',
    topicCard: '[data-testid="topic-card"]',
    topicContinueButton: '[data-testid="topic-continue-button"]',
    sessionReviewButton: '[data-testid="session-review-button"]',
    settingsButton: '[data-testid="home-settings-button"]',
    profileButton: '[data-testid="home-profile-button"]',
    extensionButton: '[data-testid="home-extension-button"]',
    strategyToggle: '[data-testid="strategy-toggle"]',
    strategyOption: (v: string) => `[data-testid="strategy-option-${v}"]`,
    groupRecCard: '[data-testid="group-rec-card"]',
    groupRecRefresh: '[data-testid="group-rec-refresh"]',
    groupRecTitle: '[data-testid="group-rec-title"]',
  },
  preStudy: {
    modal: '[data-testid="prestudy-modal"]',
    topicInput: '[data-testid="topic-input"]',
    topicSourceNew: '[data-testid="topic-source-new"]',
    topicSourceExisting: '[data-testid="topic-source-existing"]',
    existingTopicOption: '[data-testid="existing-topic-option"]',
    customTopicInput: '[data-testid="custom-topic-input"]',
    continueSuggestionCard: '[data-testid="continue-suggestion-card"]',
    userRequirementInput: '[data-testid="user-requirement-input"]',
    externalMaterialsToggle: '[data-testid="external-materials-toggle"]',
    difficultyButton: (d: string) => `[data-testid="difficulty-button-${d}"]`,
    temperatureButton: (t: string) => `[data-testid="temperature-button-${t}"]`,
    startButton: '[data-testid="start-button"]',
    cancelButton: '[data-testid="cancel-button"]',
  },
  study: {
    page: '[data-testid="study-page"]',
    messageList: '[data-testid="message-list"]',
    chatInput: '[data-testid="chat-input"]',
    sendButton: '[data-testid="send-button"]',
    archivePendingBanner: '[data-testid="archive-pending-banner"]',
    archiveButton: '[data-testid="archive-button"]',
    dismissArchiveButton: '[data-testid="dismiss-archive-button"]',
    archiveReportClose: '[data-testid="archive-report-close"]',
    archiveReportTitle: '[data-testid="archive-report-title"]',
    archiveReportBody: '[data-testid="archive-report-body"]',
    archiveLoadingOverlay: '[data-testid="archive-loading-overlay"]',
    archiveReturnHomeButton: '[data-testid="archive-return-home-button"]',
    assistantMessage: '[data-testid="assistant-message"]',
    userMessage: '[data-testid="user-message"]',
    streamErrorBanner: '[data-testid="stream-error-banner"]',
    streamRetryButton: '[data-testid="stream-retry-button"]',
    streamDismissButton: '[data-testid="stream-dismiss-button"]',
    externalMaterialsCard: '[data-testid="external-materials-card"]',
    swapPaintingButton: '[data-testid="swap-painting-button"]',
  },
  quote: {
    text: '[data-testid="quote-text"]',
    original: '[data-testid="quote-original"]',
    meta: '[data-testid="quote-meta"]',
    refreshButton: '[data-testid="quote-refresh-button"]',
  },
  briefing: {
    page: '[data-testid="briefing-page"]',
    academicLayout: '[data-testid="briefing-academic-layout"]',
    newspaperLayout: '[data-testid="briefing-newspaper-layout"]',
    themeToggle: '[data-testid="briefing-theme-toggle"]',
    historyButton: '[data-testid="briefing-history-button"]',
    regenerateButton: '[data-testid="briefing-regenerate-button"]',
    skeleton: '[data-testid="briefing-skeleton"]',
    errorDisplay: '[data-testid="briefing-error-display"]',
    cacheWriteFailedBadge: '[data-testid="briefing-cache-write-failed"]',
  },
  profile: {
    page: '[data-testid="profile-page"]',
    nameDisplay: '[data-testid="profile-name-display"]',
    textDisplay: '[data-testid="profile-text-display"]',
    topicsDisplay: '[data-testid="profile-topics-display"]',
    difficultyDisplay: '[data-testid="profile-difficulty-display"]',
    temperatureDisplay: '[data-testid="profile-temperature-display"]',
    editButton: '[data-testid="profile-edit-button"]',
    saveButton: '[data-testid="profile-save-button"]',
    cancelButton: '[data-testid="profile-cancel-button"]',
    nameInput: '[data-testid="profile-name-input"]',
    textInput: '[data-testid="profile-text-input"]',
    topicsInput: '[data-testid="profile-topics-input"]',
    difficultyButton: (d: string) => `[data-testid="profile-difficulty-${d}"]`,
    temperatureButton: (t: string) => `[data-testid="profile-temperature-${t}"]`,
    exitButton: '[data-testid="profile-exit-button"]',
  },
  settings: {
    page: '[data-testid="settings-page"]',
    apiKeyInput: '[data-testid="settings-api-key-input"]',
    apiKeyToggle: '[data-testid="settings-api-key-toggle"]',
    baseUrlInput: '[data-testid="settings-base-url-input"]',
    modelInput: '[data-testid="settings-model-input"]',
    verifyButton: '[data-testid="settings-verify-button"]',
    verifyStatus: '[data-testid="settings-verify-status"]',
    searchApiKeyInput: '[data-testid="settings-search-api-key-input"]',
    searchApiKeyToggle: '[data-testid="settings-search-api-key-toggle"]',
    searchSaveButton: '[data-testid="settings-search-save-button"]',
    libraryPathInput: '[data-testid="settings-library-path-input"]',
    selectDirectoryButton: '[data-testid="settings-select-directory-button"]',
    saveButton: '[data-testid="settings-save-button"]',
    resetButton: '[data-testid="settings-reset-button"]',
    backButton: '[data-testid="settings-back-button"]',
    errorDisplay: '[data-testid="settings-error-display"]',
  },
  library: {
    groupTab: (id: string) => `[data-testid="group-tab-${id}"]`,
    groupTabAll: '[data-testid="group-tab-all"]',
    createGroupButton: '[data-testid="create-group-button"]',
    groupRenameInput: '[data-testid="group-rename-input"]',
    groupDeleteButton: '[data-testid="group-delete-button"]',
    groupGuideButton: '[data-testid="group-guide-button"]',
    gravityField: '[data-testid="gravity-field"]',
    gravityGroupTarget: (id: string) => `[data-testid="gravity-target-${id}"]`,
    sessionViewer: '[data-testid="session-viewer"]',
    sessionViewerClose: '[data-testid="session-viewer-close"]',
    sessionViewerTitle: '[data-testid="session-viewer-title"]',
    sessionFileButton: '[data-testid="session-file-button"]',
    fableButton: '[data-testid="session-fable-button"]',
    generateFableButton: '[data-testid="generate-fable-button"]',
    diagramButton: '[data-testid="session-diagram-button"]',
    generateDiagramButton: '[data-testid="generate-diagram-button"]',
    deleteSessionButton: '[data-testid="delete-session-button"]',
    paginationPrev: '[data-testid="pagination-prev"]',
    paginationNext: '[data-testid="pagination-next"]',
    paginationDot: (i: number) => `[data-testid="pagination-dot-${i}"]`,
  },
  setupWizard: {
    stepIndicator: (s: number) => `[data-testid="wizard-step-${s}"]`,
    nextButton: '[data-testid="wizard-next-button"]',
    backButton: '[data-testid="wizard-back-button"]',
    apiKeyInput: '[data-testid="wizard-api-key-input"]',
    apiKeyToggle: '[data-testid="wizard-api-key-toggle"]',
    baseUrlInput: '[data-testid="wizard-base-url-input"]',
    modelInput: '[data-testid="wizard-model-input"]',
    libraryPathInput: '[data-testid="wizard-library-path-input"]',
    selectDirectoryButton: '[data-testid="wizard-select-directory-button"]',
    nameInput: '[data-testid="wizard-name-input"]',
    profileTextInput: '[data-testid="wizard-profile-text-input"]',
    preferredTopicsInput: '[data-testid="wizard-preferred-topics-input"]',
    errorDisplay: '[data-testid="wizard-error-display"]',
  },
  confirmDialog: {
    dialog: '[data-testid="confirm-dialog"]',
    confirmButton: '[data-testid="confirm-dialog-confirm"]',
    cancelButton: '[data-testid="confirm-dialog-cancel"]',
  },
  fableStyleDialog: {
    dialog: '[data-testid="fable-style-dialog"]',
    tagButton: (tag: string) => `[data-testid="fable-tag-${tag}"]`,
    customTagInput: '[data-testid="fable-custom-tag-input"]',
    addCustomTagButton: '[data-testid="fable-add-custom-tag-button"]',
    descriptionInput: '[data-testid="fable-description-input"]',
    startButton: '[data-testid="fable-start-button"]',
    cancelButton: '[data-testid="fable-cancel-button"]',
  },
  toast: '[data-testid="toast-message"]',
} as const
