export const SELECTORS = {
  cover: {
    nameInput: '[data-testid="cover-name-input"]',
    enterButton: '[data-testid="cover-enter-button"]',
    lightButton: '[data-testid="cover-light-button"]',
    briefingButton: '[data-testid="cover-briefing-button"]',
  },
  home: {
    greeting: '[data-testid="home-greeting"]',
    newTopicButton: '[data-testid="new-topic-button"]',
    librarySection: '[data-testid="library-section"]',
    continueUnsavedButton: '[data-testid="continue-unsaved-button"]',
    burnUnsavedButton: '[data-testid="burn-unsaved-button"]',
    unsavedSessionTitle: '[data-testid="unsaved-session-title"]',
    topicCard: '[data-testid="topic-card"]',
    topicContinueButton: '[data-testid="topic-continue-button"]',
    sessionReviewButton: '[data-testid="session-review-button"]',
    settingsButton: '[data-testid="home-settings-button"]',
    profileButton: '[data-testid="home-profile-button"]',
    extensionButton: '[data-testid="home-extension-button"]',
    strategyToggle: '[data-testid="strategy-toggle"]',
    strategyOption: (v: string) => `[data-testid="strategy-option-${v}"]`,
    groupRecCard: '[data-testid="group-rec-card"]',
    groupRecRefresh: '[data-testid="group-rec-refresh"]',
    groupRecTitle: '[data-testid="group-rec-title"]',
    wildCardCard: '[data-testid="wild-card-card"]',
    wildCardTitle: '[data-testid="wild-card-title"]',
    wildCardHook: '[data-testid="wild-card-hook"]',
    wildCardRefresh: '[data-testid="wild-card-refresh"]',
  },
  extension: {
    page: '[data-testid="extension-page"]',
    terminologyPanel: '[data-testid="terminology-panel"]',
    terminologyInput: (field: string) => `[data-testid="terminology-input-${field}"]`,
    terminologyReset: (field: string) => `[data-testid="terminology-reset-${field}"]`,
    terminologyResetAll: '[data-testid="terminology-reset-all"]',
    terminologyPreview: '[data-testid="terminology-preview"]',
    libraryDirectoryCard: '[data-testid="extension-library-directory-card"]',
    localAgentCard: '[data-testid="extension-local-agent-card"]',
    customPicturesCard: '[data-testid="extension-custom-pictures-card"]',
  },
  preStudy: {
    modal: '[data-testid="prestudy-modal"]',
    topicInput: '[data-testid="topic-input"]',
    topicSourceNew: '[data-testid="topic-source-new"]',
    topicSourceExisting: '[data-testid="topic-source-existing"]',
    existingTopicOption: '[data-testid="existing-topic-option"]',
    customTopicInput: '[data-testid="custom-topic-input"]',
    continueSuggestionCard: '[data-testid="continue-suggestion-card"]',
    userRequirementInput: '[data-testid="user-requirement-input"]',
    externalMaterialsToggle: '[data-testid="external-materials-toggle"]',
    difficultyButton: (d: string) => `[data-testid="difficulty-button-${d}"]`,
    temperatureButton: (t: string) => `[data-testid="temperature-button-${t}"]`,
    startButton: '[data-testid="start-button"]',
    cancelButton: '[data-testid="cancel-button"]',
  },
  study: {
    page: '[data-testid="study-page"]',
    messageList: '[data-testid="message-list"]',
    chatInput: '[data-testid="chat-input"]',
    sendButton: '[data-testid="send-button"]',
    archivePendingBanner: '[data-testid="archive-pending-banner"]',
    archiveButton: '[data-testid="archive-button"]',
    dismissArchiveButton: '[data-testid="dismiss-archive-button"]',
    archiveReportClose: '[data-testid="archive-report-close"]',
    archiveReportTitle: '[data-testid="archive-report-title"]',
    archiveReportBody: '[data-testid="archive-report-body"]',
    archiveLoadingOverlay: '[data-testid="archive-loading-overlay"]',
    archiveReturnHomeButton: '[data-testid="archive-return-home-button"]',
    assistantMessage: '[data-testid="assistant-message"]',
    userMessage: '[data-testid="user-message"]',
    streamErrorBanner: '[data-testid="stream-error-banner"]',
    streamRetryButton: '[data-testid="stream-retry-button"]',
    streamDismissButton: '[data-testid="stream-dismiss-button"]',
    externalMaterialsCard: '[data-testid="external-materials-card"]',
    externalSummaryOpen: '[data-testid="external-summary-open"]',
    externalSummaryPanel: '[data-testid="external-summary-panel"]',
    externalSummaryClose: '[data-testid="external-summary-close"]',
    externalSummarySource: (n: number) => `[data-testid="external-summary-source-${n}"]`,
    swapPaintingButton: '[data-testid="swap-painting-button"]',
  },
  articleAssistant: {
    tab: '[data-testid="article-assistant-tab"]',
    chatWindow: '[data-testid="article-assistant-chat-window"]',
    input: '[data-testid="article-assistant-input"]',
    searchBtn: '[data-testid="article-assistant-search-btn"]',
    sendBtn: '[data-testid="article-assistant-send-btn"]',
    stopBtn: '[data-testid="article-assistant-stop-btn"]',
    divider: '[data-testid="article-assistant-divider"]',
    dividerToggle: '[data-testid="article-assistant-divider-toggle"]',
    guideChunk: '[data-testid="guide-chunk"]',
    bodyChunk: '[data-testid="article-body-chunk"]',
    bodyChunkPlaque: '[data-testid="article-chunk-plaque"]',
    swapPaintingButton: '[data-testid="briefing-swap-painting-button"]',
    anthropicSwapPaintingButton: '[data-testid="anthropic-swap-painting-button"]',
    socraticBtn: '[data-testid="article-assistant-socratic-btn"]',
    thinkingBtn: '[data-testid="article-assistant-thinking-btn"]',
    pendingSelection: '[data-testid="pending-selection"]',
    selectionCancelBtn: '[data-testid="selection-cancel-btn"]',
    chatMessage: '[data-testid="chat-message"]',
    chatMessageSelection: '[data-testid="chat-message-selection"]',
    reasoningBlock: '[data-testid="reasoning-block"]',
    searchErrorBanner: '[data-testid="assistant-search-error"]',
  },
  quote: {
    text: '[data-testid="quote-text"]',
    original: '[data-testid="quote-original"]',
    meta: '[data-testid="quote-meta"]',
    refreshButton: '[data-testid="quote-refresh-button"]',
  },
  briefing: {
    page: '[data-testid="briefing-page"]',
    academicLayout: '[data-testid="briefing-academic-layout"]',
    newspaperLayout: '[data-testid="briefing-newspaper-layout"]',
    themeToggle: '[data-testid="briefing-theme-toggle"]',
    receiveDigestButton: '[data-testid="briefing-receive-digest-button"]',
    listColumn: '[data-testid="briefing-list-column"]',
    listColumnToggle: '[data-testid="briefing-list-column-toggle"]',
    dateColumn: '[data-testid="briefing-date-column"]',
    dateItem: (date: string) => `[data-testid="briefing-date-item-${date}"]`,
    dateFlame: (date: string) => `[data-testid="briefing-date-flame-${date}"]`,
    readingPane: '[data-testid="briefing-reading-pane"]',
    jobReadingPane: '[data-testid="job-briefing-reading-pane"]',
    dateTodayMini: '[data-testid="briefing-date-today-mini"]',
    sourceExpandToggle: '[data-testid="briefing-source-expand-toggle"]',
    anthropicListRailThumb: '[data-testid="anthropic-list-rail-thumb"]',
    fontSizeDecrease: '[data-testid="briefing-font-size-decrease"]',
    fontSizeIncrease: '[data-testid="briefing-font-size-increase"]',
    sourceStatus: '[data-testid="briefing-source-status"]',
    skeleton: '[data-testid="briefing-skeleton"]',
    errorDisplay: '[data-testid="briefing-error-display"]',
    retryButton: '[data-testid="briefing-retry-button"]',
    darkOverlay: '[data-testid="briefing-dark-overlay"]',
    quoteText: '[data-testid="quote-text"]',
    constellation: '[data-testid="briefing-constellation"]',
    constellationWell: '[data-testid="briefing-constellation-well"]',
    progress: '[data-testid="briefing-progress"]',
    progressStep: (key: string) => `[data-testid="briefing-progress-step-${key}"]`,
    cancelButton: '[data-testid="briefing-cancel-button"]',
    generatedAt: '[data-testid="briefing-generated-at"]',
    cacheWriteFailedBadge: '[data-testid="briefing-cache-write-failed"]',
    swapPaintingButton: '[data-testid="briefing-swap-painting-button"]',
    anthropicSwapPaintingButton: '[data-testid="anthropic-swap-painting-button"]',
    surfaceBackground: '[data-testid="surface-background"]',
    markdownBody: '[data-testid="briefing-markdown-body"]',
    sourceSidebar: '[data-testid="briefing-source-sidebar"]',
    sourceSidebarToggle: '[data-testid="briefing-sidebar-toggle"]',
    railControls: '[data-testid="briefing-rail-controls"]',
    contentShell: '[data-testid="briefing-content-shell"]',
    sourceGroup: '[data-testid="briefing-source-group"]',
    sourceCard: '[data-testid="briefing-source-card"]',
    sourceCardLink: '[data-testid="briefing-source-card-link"]',
    sourceDigestButton: '[data-testid="briefing-source-digest"]',
    sourceAnthropicButton: '[data-testid="briefing-source-anthropic"]',
    sourceJobBriefingButton: '[data-testid="briefing-source-job-briefing"]',
    transferToWriting: '[data-testid="transfer-to-writing"]',
    receiveJobButton: '[data-testid="briefing-receive-job-button"]',
    jobProfileEntry: '[data-testid="job-profile-panel-trigger"]',
    dateDelete: '[data-testid="briefing-date-delete"]',
    dateMenu: '[data-testid="briefing-date-menu"]',
    confirmDialog: '[data-testid="confirm-dialog"]',
    confirmDialogConfirm: '[data-testid="confirm-dialog-confirm"]',
    jobCard: '[data-testid="job-briefing-card"]',
    jobEvent: '[data-testid="job-briefing-event"]',
    jobQuestion: '[data-testid="job-briefing-question"]',
    anthropicPanel: '[data-testid="anthropic-blog-panel"]',
    anthropicRefreshButton: '[data-testid="anthropic-refresh-button"]',
    anthropicArticleRow: '[data-testid="anthropic-article-row"]',
    anthropicArticleTitle: '[data-testid="anthropic-article-title"]',
    anthropicSectionTag: '[data-testid="anthropic-section-tag"]',
    anthropicArticleSaved: '[data-testid="anthropic-article-saved"]',
    anthropicArticleReader: '[data-testid="anthropic-article-reader"]',
    anthropicReaderTitle: '[data-testid="anthropic-reader-title"]',
    anthropicReaderSummary: '[data-testid="anthropic-reader-summary"]',
    anthropicErrorMessage: '[data-testid="anthropic-error-message"]',
    anthropicReaderImage: '[data-testid="anthropic-article-reader"] [data-testid="md-image"]',
    anthropicNewArticlesPrompt: '[data-testid="anthropic-new-articles-prompt"]',
    anthropicListCheckError: '[data-testid="anthropic-list-check-error"]',
    anthropicConstitutionPill: '[data-testid="anthropic-constitution-pill"]',
    constitutionReportView: '[data-testid="constitution-report-view"]',
    constitutionReportFrame: '[data-testid="constitution-report-frame"]',
  },
  profile: {
    page: '[data-testid="profile-page"]',
    nameDisplay: '[data-testid="profile-name-display"]',
    textDisplay: '[data-testid="profile-text-display"]',
    topicsDisplay: '[data-testid="profile-topics-display"]',
    difficultyDisplay: '[data-testid="profile-difficulty-display"]',
    temperatureDisplay: '[data-testid="profile-temperature-display"]',
    editButton: '[data-testid="profile-edit-button"]',
    saveButton: '[data-testid="profile-save-button"]',
    cancelButton: '[data-testid="profile-cancel-button"]',
    nameInput: '[data-testid="profile-name-input"]',
    textInput: '[data-testid="profile-text-input"]',
    topicsInput: '[data-testid="profile-topics-input"]',
    difficultyButton: (d: string) => `[data-testid="profile-difficulty-${d}"]`,
    temperatureButton: (t: string) => `[data-testid="profile-temperature-${t}"]`,
    exitButton: '[data-testid="profile-exit-button"]',
  },
  settings: {
    page: '[data-testid="settings-page"]',
    apiKeyInput: '[data-testid="settings-api-key-input"]',
    apiKeyToggle: '[data-testid="settings-api-key-toggle"]',
    baseUrlInput: '[data-testid="settings-base-url-input"]',
    modelInput: '[data-testid="settings-model-input"]',
    verifyButton: '[data-testid="settings-verify-button"]',
    verifyStatus: '[data-testid="settings-verify-status"]',
    searchApiKeyInput: '[data-testid="settings-search-api-key-input"]',
    searchApiKeyToggle: '[data-testid="settings-search-api-key-toggle"]',
    searchSaveButton: '[data-testid="settings-search-save-button"]',
    libraryPathInput: '[data-testid="settings-library-path-input"]',
    selectDirectoryButton: '[data-testid="settings-select-directory-button"]',
    saveButton: '[data-testid="settings-save-button"]',
    resetButton: '[data-testid="settings-reset-button"]',
    backButton: '[data-testid="settings-back-button"]',
    errorDisplay: '[data-testid="settings-error-display"]',
  },
  library: {
    groupTab: (id: string) => `[data-testid="group-tab-${id}"]`,
    groupTabAll: '[data-testid="group-tab-all"]',
    createGroupButton: '[data-testid="create-group-button"]',
    groupRenameInput: '[data-testid="group-rename-input"]',
    groupDeleteButton: '[data-testid="group-delete-button"]',
    groupGuideButton: '[data-testid="group-guide-button"]',
    groupGuidePopover: '[data-testid="group-guide-popover"]',
    gravityField: '[data-testid="gravity-field"]',
    gravityGroupTarget: (id: string) => `[data-testid="gravity-target-${id}"]`,
    sessionViewer: '[data-testid="session-viewer"]',
    sessionViewerClose: '[data-testid="session-viewer-close"]',
    sessionViewerTitle: '[data-testid="session-viewer-title"]',
    sessionFileButton: '[data-testid="session-file-button"]',
    fableButton: '[data-testid="session-fable-button"]',
    generateFableButton: '[data-testid="generate-fable-button"]',
    diagramButton: '[data-testid="session-diagram-button"]',
    generateDiagramButton: '[data-testid="generate-diagram-button"]',
    deleteSessionButton: '[data-testid="delete-session-button"]',
    paginationPrev: '[data-testid="pagination-prev"]',
    paginationNext: '[data-testid="pagination-next"]',
    paginationDot: (i: number) => `[data-testid="pagination-dot-${i}"]`,
  },
  setupWizard: {
    stepIndicator: (s: number) => `[data-testid="wizard-step-${s}"]`,
    nextButton: '[data-testid="wizard-next-button"]',
    backButton: '[data-testid="wizard-back-button"]',
    apiKeyInput: '[data-testid="wizard-api-key-input"]',
    apiKeyToggle: '[data-testid="wizard-api-key-toggle"]',
    baseUrlInput: '[data-testid="wizard-base-url-input"]',
    modelInput: '[data-testid="wizard-model-input"]',
    libraryPathInput: '[data-testid="wizard-library-path-input"]',
    selectDirectoryButton: '[data-testid="wizard-select-directory-button"]',
    nameInput: '[data-testid="wizard-name-input"]',
    profileTextInput: '[data-testid="wizard-profile-text-input"]',
    preferredTopicsInput: '[data-testid="wizard-preferred-topics-input"]',
    errorDisplay: '[data-testid="wizard-error-display"]',
  },
  confirmDialog: {
    dialog: '[data-testid="confirm-dialog"]',
    confirmButton: '[data-testid="confirm-dialog-confirm"]',
    cancelButton: '[data-testid="confirm-dialog-cancel"]',
  },
  fableStyleDialog: {
    dialog: '[data-testid="fable-style-dialog"]',
    tagButton: (tag: string) => `[data-testid="fable-tag-${tag}"]`,
    customTagInput: '[data-testid="fable-custom-tag-input"]',
    addCustomTagButton: '[data-testid="fable-add-custom-tag-button"]',
    descriptionInput: '[data-testid="fable-description-input"]',
    startButton: '[data-testid="fable-start-button"]',
    cancelButton: '[data-testid="fable-cancel-button"]',
  },
  toast: '[data-testid="toast-message"]',
  scout: {
    panel: '[data-testid="scout-panel"]',
    tabChat: '[data-testid="scout-tab-chat"]',
    tabArticles: '[data-testid="scout-tab-articles"]',
    chatEmpty: '[data-testid="scout-chat-empty"]',
    chatView: '[data-testid="scout-chat-view"]',
    chatInput: '[data-testid="scout-chat-input"]',
    chatSend: '[data-testid="scout-chat-send"]',
    chatAbort: '[data-testid="scout-chat-abort"]',
    newConversation: '[data-testid="scout-new-conversation"]',
    message: (role: string) => `[data-testid="scout-message-${role}"]`,
    candidateCards: '[data-testid="scout-candidate-cards"]',
    candidate: (i: number) => `[data-testid="scout-candidate-${i}"]`,
    confirmCandidates: '[data-testid="scout-confirm-candidates"]',
    confirmAllCandidates: '[data-testid="scout-confirm-all-candidates"]',
    articleRow: '[data-testid="scout-article-row"]',  // fallback for backward compat
    articleRowByUrl: (url: string) => `[data-testid="scout-article-row-${url}"]`,
    articleTitle: '[data-testid="article-row-title"]',
    articleDelete: '[data-testid="article-row-delete"]',
    conversation: (id: string) => `[data-testid="scout-conversation-${id}"]`,
    conversationDelete: (id: string) => `[data-testid="scout-conversation-delete-${id}"]`,
    conversationRenameInput: '[data-testid="scout-conversation-rename-input"]',
    sourceButton: '[data-testid="briefing-source-scout"]',
  },
  annotations: {
    ghostPen: '[data-testid="anno-ghost-pen"]',
    selectionHighlight: '[data-testid="anno-selection-highlight"]',
    noteCard: '[data-testid="anno-note-card"]',
    noteTextarea: '[data-testid="anno-note-textarea"]',
    saveButton: '[data-testid="anno-save-button"]',
    deleteButton: '[data-testid="anno-delete-button"]',
    markerPen: '[data-testid="anno-marker-pen"]',
    markedText: '[data-testid="anno-marked-text"]',
    listButton: '[data-testid="annotation-list-button"]',
    listItem: '[data-testid="annotation-list-item"]',
  },
  writing: {
    sourceButton: '[data-testid="briefing-source-writing"]',
    listTabArticles: '[data-testid="writing-list-tab-articles"]',
    listTabRepository: '[data-testid="writing-list-tab-repository"]',
    newFileButton: '[data-testid="writing-new-file"]',
    newFolderButton: '[data-testid="writing-new-folder"]',
    importFilesButton: '[data-testid="writing-import-files"]',
    treeNode: '[data-testid="writing-tree-node"]',
    editor: '[data-testid="writing-editor"]',
    saveStatus: '[data-testid="writing-save-status"]',
    boardEmpty: '[data-testid="writing-board-empty"]',
    collapsedArticlesCount: '[data-testid="writing-collapsed-articles-count"]',
    collapsedRepositoryCount: '[data-testid="writing-collapsed-repository-count"]',
    assistantCollapsed: '[data-testid="article-assistant-divider-toggle"]',
    assistantPanel: '[data-testid="writing-assistant-panel-content"]',
    assistantInput: '[data-testid="writing-assistant-input"]',
    assistantSendBtn: '[data-testid="writing-assistant-send-btn"]',
    assistantStopBtn: '[data-testid="writing-assistant-stop-btn"]',
    assistantSearchBtn: '[data-testid="writing-assistant-search-btn"]',
    assistantThinkingBtn: '[data-testid="writing-assistant-thinking-btn"]',
    assistantInsertBtn: '[data-testid="writing-assistant-insert-btn"]',
    assistantCloseBtn: '[data-testid="writing-assistant-close-btn"]',
    assistantMessages: '[data-testid="writing-assistant-messages"]',
    assistantResizeHandle: '[data-testid="article-assistant-divider"]',
    toolbarBold: '[data-testid="writing-toolbar-bold"]',
    toolbarItalic: '[data-testid="writing-toolbar-italic"]',
    toolbarStrikethrough: '[data-testid="writing-toolbar-strikethrough"]',
    toolbarBlockquote: '[data-testid="writing-toolbar-blockquote"]',
    toolbarBulletList: '[data-testid="writing-toolbar-bullet-list"]',
    toolbarOrderedList: '[data-testid="writing-toolbar-ordered-list"]',
    toolbarHr: '[data-testid="writing-toolbar-hr"]',
    toolbarHeading: '[data-testid="writing-toolbar-heading"]',
    toolbarColor: '[data-testid="writing-toolbar-color"]',
    headingOption: '[data-testid="writing-heading-option"]',
    colorOption: '[data-testid="writing-color-option"]',
  },
} as const
